# Generated by Django 5.0.6 on 2025-12-02 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('extra_phone', models.CharField(blank=True, max_length=50, verbose_name='Qo‘shimcha telefon')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('bank', 'Bank o‘tkazmasi')], default='cash', max_length=20, verbose_name='To‘lov turi')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilindi'), ('delivering', 'Yetkazilmoqda'), ('finished', 'Yakunlangan')], default='new', max_length=20, verbose_name='Holat')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Umumiy summa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
