# Generated by Django 5.0.6 on 2025-12-03 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_featuredcategory'),
        ('catalog', '0003_merge_0002_banner_0002_category_parent'),
    ]

    operations = [
    ]
