# Generated by Django 5.0.6 on 2025-12-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_merge_20251203_0914'),
        ('catalog', '0005_author_photo'),
    ]

    operations = [
    ]
