# Generated by Django 5.0.6 on 2025-12-03 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_merge_0004_merge_20251203_0914_0005_author_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'Muallif', 'verbose_name_plural': 'Mualliflar'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kitob', 'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Tarjimai hol'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalog.author', verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_format',
            field=models.CharField(blank=True, choices=[('hard', 'Qattiq muqova'), ('soft', 'Yumshoq muqova')], max_length=10, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalog.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Muqova'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Tavsiya etilgan'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Betlar soni'),
        ),
        migrations.AlterField(
            model_name='book',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Sotib olish narxi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Sotish narxi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='book',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Ko‘rishlar soni'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
