# Generated by Django 5.0.6 on 2025-12-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_aboutpage'),
        ('catalog', '0007_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
    ]
